name: Develop Action

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze