name: Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2	
        with:	
          repository: flutter/flutter	
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
  
  build-design-system:
    runs-on: macos-latest
    needs: setup
    env: 
      working-directory: ./thought_design_system
      FLUTTER_HOME: /Users/runner/hostedtoolcache/flutter/bin

    steps:
      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test

  build-sample:
    runs-on: macos-latest
    needs: setup
    env: 
      working-directory: ./sample
      FLUTTER_HOME: /Users/runner/hostedtoolcache/flutter/bin

    steps:
      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk

      - name: Build IOS
        run: flutter build ios
