name: Master Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - run: cd sample

      - name: Build flutter apk
        run: flutter build apk